on: [push, pull_request]
jobs:
  install_symfony:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.1']

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up php the project
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, mysql, xml, ctype, intl, iconv, filter, gd, json, pdo

      - name: install packages
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Checking symfony installation
        run: php bin/console about

      - name: Check PSR12 code style (PHP_CodeSniffer)
        uses: chekalsky/phpcs-action@v1.2.0
        with:
          enable_warnings: true
          installed_paths: '${{ github.workspace }}/vendor/squizlabs/php_codesniffer'
          phpcs_bin_path: './vendor/bin/phpcs src --ignore="Migrations/"'
